### ISSUE TITLE
Dependency issue: scikit-image is dependent on SciPy on Windows

### ISSUE THREAD

**Issue by ericrickydixon** [harris-helios/helios-sdk-python#3]
The Python library SciPy is not easily installed in the Windows environment.  Is it possible to remove the base class dependency?  Compared to OSX and Linux, building SciPy on Windows is difficult, there is a lack of compatible, open-source libraries like LAPACK or ATLAS that are necessary to build the library.

**Comment by mab4058** [comment]
You should not have to build SciPy from scratch on your machine.  A pip or conda install will suffice. 

`pip install scipy`
or
`conda install scipy`

If you tried this and are still having issues I would make sure your Python installation (probably Conda+Anaconda)  isn't broken and if it is do a fresh install of [Anaconda](https://www.continuum.io/downloads).

**Comment by mab4058** [comment]
After more research I deleted my original comment.  

According to the official Scipy docs:
> Windows does not have any package manager analogous to that in Linux, so installing one of the scientific Python distributions mentioned above is preferred. However, if that is not an option, Christoph Gohlke provides [pre-built Windows installers](http://www.lfd.uci.edu/~gohlke/pythonlibs) for many Python packages, including all of the core SciPy stack, which work extremely well.

> For most users, especially on Windows, the easiest way to install the packages of the SciPy stack is to download one of these Python distributions, which include all the key packages:
>- Anaconda: A free distribution for the SciPy stack. Supports Linux, Windows and Mac.
>- Enthought Canopy: The free and commercial versions include the core SciPy stack packages. Supports Linux, Windows and Mac.
>- Python(x,y): A free distribution including the SciPy stack, based around the Spyder IDE. Windows only.
>- WinPython: A free distribution including the SciPy stack. Windows only.
>- Pyzo: A free distribution based on Anaconda and the IEP interactive development environment. Supports Linux, Windows and Mac.

The easiest option is to install [Anaconda](https://www.continuum.io/downloads).  This comes with the [full SciPy stack](https://www.scipy.org/stackspec.html#stackspec)

Also, since commit 2c8a67684e3dd5fc50267c6b1416a937083bebfc the scipy requirement has been removed for now. But notice that since 1bf24a59b4edfd2bf5840234c989fbedcfcf0091, numpy is now a requirement.  It is safe to assume that both SciPy and Numpy will most likely be necessary at some point.
